name: vcdemo
services:
  vcdemo:
    image: gcr.io/distroless/static-debian12
    container_name: vcdemo
    user: 1000:1000
    restart: unless-stopped
    ports:
      - "3030:3030"
      - "8090:8090"
      - "9999:9999"
      - "9998:9998"
    volumes:
      - .:/dome
    working_dir: /dome
    entrypoint: ["/dome/vcdemo", "serve"]

